---
title: Introduction to STA5069Z
subtitle: Modern multivariate statistical techniques
author: Miguel Rodo
date: "2024-02-12"
bibliography: zotero.bib
format:
  beamer:
    embed-resources: true
    aspectratio: 169
    urlcolor: cyan
    linkcolor: blue
    filecolor: magenta
    include-in-header:
      file: preamble.tex
---

## Welcome to STA5069Z

- This course follows on from the honours module in multivariate statistics. It is aimed at looking at the application of multivariate techniques to modern-day data problems, including big data problems. Techniques introduced at honours level will be reviewed and extended and new techniques will be introduced.
  - See [course website](https://sebnemer.github.io/english/courses/multivariate/) for specific topics coverered.

- **Lecturers**
  - Mr Miguel Rodo (PD Hahn 5.52)
  - Dr Sebnem Er (PD Hahn 5.55)

\addtocounter{framenumber}{-1}

## Key references

- Primary: @izenman08
  - Available (for purchase) at [Springer](https://www.springer.com/gp/book/9780387781884) and [Amazon](https://www.amazon.com/Modern-Multivariate-Statistical-Techniques-Classification/dp/0387781889)
- Also used: @hastie_etal09
  - Available for free at [Hastie's own website](https://hastie.su.domains/ElemStatLearn/)
- Paper references will be provided as we go

## Course structure: lectures

- The [course website](https://sebnemer.github.io/english/courses/multivariate/) has all the information you need.

**Format**

- Each lecture will cover a new set of multivariate techniques.
- These is a *lot* of content, which will not all be covered in lectures.
- As such, significant self study is required.
  - Lecture slides and associated recommended readings will be provided in advance.
- During lectures, we will cover key concepts, tackle student questions and review tutorial solutions.

**Venue and timing**

- Lectures will be 4-5.45pm on Mondays and Wednesdays in PD Hahn 4.26 (the Quiet Room).

## Course structure: practice and testing

**Tutorials**

- For each lecture, tutorials (class exercises) to implement the methods discussed in `R` will be provided.

**Assignment**

- 10-page summary report on applying modern multivariate methods to particular problem areas, such as bioinformatics, finance, or marketing.

**Exam**

- *Format*: Open-book take-home exam.
- *DP requirement*: lecture attendance and timely submission of tutorials.
- *Pass requirement*: Average of 50% across exam and assignment, with 40% sub-minimum for each.

## Assignment

- See [course website](https://sebnemer.github.io/english/courses/multivariate/assignment-description.html) for details.
- A template repository is available [here](https://github.com/MiguelRodo/Template24STA5069Z) for creating a GitHub repo with the desired structure for the project.

## Technical prerequisites

- Primarily, linear algebra. In particular:
  - Matrix norms
  - Eigendecomposition
  - SVD

## References
